# Generated by Django 3.1.7 on 2021-03-03 16:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('channel_id', models.CharField(max_length=128, unique=True)),
                ('status', models.CharField(choices=[('Queued', 'Queued'), ('Downloading Files from S3', 'Downloading Files from S3'), ('Processing', 'Processing'), ('Uploading the output to S3', 'Uploading the output to S3'), ('Completed', 'Completed')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
