# Generated by Django 3.1.7 on 2021-03-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelstatus',
            name='aws_key',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
